version: "2"
services:
  app:
    build: ./app
    links:
      - db
      - ipcamera
    ports:
      - "5000:5000"

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
  ipcamera:
    build: ./ipcamera
    network_mode: "host"
    volumes: 
      - ./ipcamera/loop.mp4:/loop.mp4
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root